version: '3.4'

services:
  mineralkingdomapi:
    image: ${DOCKER_REGISTRY-}mineralkingdomapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MAILTRAP_USERNAME=${MAILTRAP_USERNAME}
      - MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10000:10000"  # Map port 10000 on the host to port 10000 in the container
    networks:
      - mineralkingdombackend-network

networks:
  mineralkingdombackend-network:
    driver: bridge
